version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://asmadmin:zAdmin01@postgres:5432/bookings
      REDIS_URL: redis://:your_redis_password@redis:6379
      JWT_SECRET: your_strong_secret_key_here
      CORS_ORIGIN: http://localhost:3000
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start:prod
      "

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: asmadmin
      POSTGRES_PASSWORD: zAdmin01
      POSTGRES_DB: bookings
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U asmadmin -d bookings']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass your_redis_password
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'your_redis_password', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '6379:6379'

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - redisinsight:/db

volumes:
  postgres_data:
  redisinsight:
